// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace vsExtensions
{
    internal sealed partial class Vsix
    {
        public const string Id = "vsExtensions.edc5b211-25a9-4451-842a-46b21b4263aa";
        public const string Name = "vsExtensions";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
